default: &default
  adapter: postgresql
  encoding: unicode
  user: rails
  passwrd: rails
  pool: 5

development:
  <<: *default
  database: test-ora_development

test:
  <<: *default
  database: test-ora_test